### ISSUE TITLE
Some localizations are missing

### ISSUE THREAD

**Issue by Orlandoxx** [E2OpenPlugins/e2openplugin-Foreca#62]
Hello,

is it possible to make : Feels Like:, Precip chance: and Humidity: translatable ? Thank you !

**Comment by jbleyel** [comment]
Is this fixed?

**Comment by Orlandoxx** [comment]
Unfortunately not.

**Comment by MrServo** [comment]
OK! I will overwork this issue in the plugin...

**Comment by Orlandoxx** [comment]
Finland

**Comment by MrServo** [comment]
You can try it for your own. Copy this string into your browser and play around with the country settings. In this example it is '**de**' for Germany. Try '**fr**' for France and then try 'fi' or other possibilities. In case you got it, please tell me in order to map the E2-setting to 'Foreca'-setting

https://www.foreca.hr/Germany/Berlin?lang=de&details=20230328&units=metrickmh&tf=24h

**Comment by Orlandoxx** [comment]
Ok, I'm back at home friday. Then I can make tests what is needed.

**Comment by Orlandoxx** [comment]
Hello,

with https://www.foreca.hr/Germany/Berlin?**lang=fi**&details=20230328&units=metrickmh&tf=24h everything is in english.

**Comment by MrServo** [comment]
Thanks for your investigations. I will modify plugin on order to use the Finnish URL in case of language settings "Finland"...

**Comment by Orlandoxx** [comment]
Thanx !

**Comment by MrServo** [comment]
The Finnish homepage '**www.foreca.fi**' (JSON based) is completely different from the regular one (HTML-based). That's why it's just too much effort for me to implement a separate version exclusively for the Finnish homepage. Unfortunately, I can't go exclusively through the Finnish homepage (JSON based) either because it doesn't support other languages, it then switches to a different URL (HTML-based) when I change languages.

**Comment by Orlandoxx** [comment]
I understand, no problem. Thank you for clearing it out.

**Comment by MrServo** [comment]
It's already done. ;)
In case the FORECA-plugin will not work one day (is foreseeable), we will change the plugin to JSON as well and then it will probably work with the Finnish homepage as well. Anyway, we won't lose sight of that... ;)
If you like, you can close this issue here.

**Comment by Orlandoxx** [comment]
Wow ! Thank you very much. I will close this issue.
